### ISSUE TITLE
Errors out with self-signed certificate

### ISSUE THREAD

**Issue by marquiswang** [yakyak/yakyak#1051]
My office uses a firewall which decrypts and re-signs HTTPS traffic. This causes YakYak to fail to connect with the following error:

```
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2019-03-25 12:37:04 INFO fetchPvt failed SELF_SIGNED_CERT_IN_CHAIN
connect_failed { Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
error connecting { Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

It would be nice to have the option to ignore this.

**Comment by gpanders** [comment]
@marquiswang Did you ever find a solution to this? I am in the exact same situation.

**Comment by marquiswang** [comment]
@gpanders I added the following code to `/Applications/YakYak.app/Contents/Resources/app/main.js` at line 36, which disabled the certificate error check.

```js
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
  // SSL/TSL: this is the self signed certificate support
  app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
      // On certificate error we disable default behaviour (stop loading the page)
      // and we then say "it is all fine - true" to the callback
      console.log('Ignoring certificate error')
      event.preventDefault();
      callback(true);
  });
```
