### ISSUE TITLE
1.5.4 cannot connect due to "HPE_HEADER_OVERFLOW"

### ISSUE THREAD

**Issue by qqldd** [yakyak/yakyak#1114]
I am running on Mac 10.15.2 and Debian. They stuck on connecting screen. From linux command line, I got this error again and again

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed Error: Parse Error: Header overflow
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17) {
  bytesParsed: 9194,
  code: 'HPE_HEADER_OVERFLOW',
  reason: 'Header overflow',
  rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 58 2d 47 6f 6f 67 6c 65 2d 4e 65 74 6d 6f 6e 2d 4c 61 62 65 6c 3a 20 2f 62 6e 73 2f 70 68 2f 62 6f ... 13739 more bytes>
}
error connecting Error: Parse Error: Header overflow
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17) {
  bytesParsed: 9194,
  code: 'HPE_HEADER_OVERFLOW',
  reason: 'Header overflow',
  rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 58 2d 47 6f 6f 67 6c 65 2d 4e 65 74 6d 6f 6e 2d 4c 61 62 65 6c 3a 20 2f 62 6e 73 2f 70 68 2f 62 6f ... 13739 more bytes>
}
```

**Comment by averissimo** [comment]
Can you try 2 things?

1. Remove config files from yakyak *(in debian should be in $HOME/.config/yakyak
1. Try v1.5.5-beta available in releases?

**Comment by qqldd** [comment]
I tried both on Debian:
1. After remove ~/.config/yakyak, it show login screen. After login, the same issue
2. Tried 1.5.5-beta and removed ~/.config/yakyak, same issue.

**Comment by averissimo** [comment]
I really have no idea how to approach this, it seems that you are receiving a response *(at the protocol level)* that is not supported by our client *(yakyak/hangupsjs)*.

**Comment by qqldd** [comment]
Hmm, seems yakyak-1.5.4 works well on my MacOS right now. Not sure why. Let me see if I need to reboot my debian machine.
