### ISSUE TITLE
Fatal Error in Main Process

### ISSUE THREAD

**Issue by 4nanook** [yakyak/yakyak#1253]
This is on a Ubuntu Focal machine 20.04.1, using 5.9.0 kernel, and Mate Desktop.

yakyak
Starting Yakyak v1.5.10...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/usr/lib/yakyak/resources/app.asar/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /usr/lib/yakyak/resources/app.asar/ui/models/conv.js:42:34
      at add (/usr/lib/yakyak/resources/app.asar/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/usr/lib/yakyak/resources/app.asar/ui/models/conv.js:522:17)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:54:10)
      at doAction (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:45:68)
      at action (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:39:14)
      at file:///usr/lib/yakyak/resources/app.asar/ui/app.js:209:23
      at EventEmitter.<anonymous> (file:///usr/lib/yakyak/resources/app.asar/ui/app.js:107:16)
      at EventEmitter.emit (events.js:223:5)
} 
--- End of error message in YakYak window.
--------
Goodbye

**Comment by lividhen** [comment]
i have this same error. windows 10.

**Comment by HomerSp** [comment]
See #1234 for more info and a fix.

**Comment by lividhen** [comment]
> See #1234 for more info and a fix.

Hey thanks! This fixed the issue.
