### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'Menu' of undefined"

### ISSUE THREAD

**Issue by vincenzocaselli** [yakyak/yakyak#1254]
I am using yakyak for many months now without a problem, but in the last few days I am getting this error when it stats:

```
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'Menu' of undefined",
  url: '/usr/share/yakyak/app/ui/views/menu.js',
  lineNo: 6,
  columnNo: 17,
  error: TypeError: Cannot read property 'Menu' of undefined
      at Object.<anonymous> (/usr/share/yakyak/app/ui/views/menu.js:6:17)
      at Object.<anonymous> (/usr/share/yakyak/app/ui/views/menu.js:802:4)
      at Object.<anonymous> (/usr/share/yakyak/app/ui/views/menu.js:806:3)
      at Module._compile (internal/modules/cjs/loader.js:1145:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
      at Module.load (internal/modules/cjs/loader.js:981:32)
      at Module._load (internal/modules/cjs/loader.js:881:14)
      at Function.Module._load (electron/js2c/asar.js:769:28)
      at Module.require (internal/modules/cjs/loader.js:1023:19)                                                                                                                                    at require (internal/modules/cjs/helpers.js:77:18)                                                                                                                                       } 
--- End of error message in YakYak window.
```
Any hints?

**Comment by tthordarson** [comment]
I fixed the issue in my personal fork

https://github.com/tthordarson/yakyak/commit/78873107eb8919560e7a26a6f79588c04d17d11b

**Comment by tthordarson** [comment]
If the original authors want me to I could create a pull request with this fix. Only that it looks to me as if they are no longer maintaining this project and there are already [22 pull requests](https://github.com/yakyak/yakyak/pulls) that aren't getting merged.

**Comment by HomerSp** [comment]
@tthordarson If you would like to do a PR, please do - I'll get it merged asap.

**Comment by tthordarson** [comment]
Ok boss, I just created a pull request
#1286

**Comment by averissimo** [comment]
@tthordarson the project just got new _(and very capable)_ blood with @HomerSp picking up the steering wheel :)

There are multiple _"meta"_ pull requests open at the moment, while others are either awaiting some change requests or incomplete implementations _(I'm guilty of at least two of them with off the record and a react transition)_

If you're motivated please contribute with pull requests :+1:
