### ISSUE TITLE
Fatal error on Kali Linux

### ISSUE THREAD

**Issue by mdgaziur** [yakyak/yakyak#1259]
Issue encountered on Kali Linux 2020.4 when logging in with regular gmail account.

On YakYak window, there is en error when launching which says: ```Possible fatal error on main process, Yakyak could stop working as expected```

Log:
```
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open i915 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: i915
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/opt/yakyak/resources/app/ui/models/conv.js',
  lineNo: 520,
  columnNo: 32,
  error: TypeError: Cannot read property 'length' of undefined
      at Object._initFromConvStates (/opt/yakyak/resources/app/ui/models/conv.js:520:32)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:54:10)
      at doAction (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:45:68)
      at action (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:39:14)
      at file:///opt/yakyak/resources/app/ui/app.js:207:23
      at EventEmitter.<anonymous> (file:///opt/yakyak/resources/app/ui/app.js:105:16)
      at EventEmitter.emit (events.js:223:5)
      at Object.onMessage (electron/js2c/renderer_init.js:2093:16)
} 
--- End of error message in YakYak window.

```

**Comment by lividhen** [comment]
https://github.com/yakyak/yakyak/issues/1234
Just a quick reminder, double check to see if people have the same issue! It may have been solved! 😊

**Comment by HomerSp** [comment]
Closing since this has been fixed
