### ISSUE TITLE
Uncaught Error: Rejected (update:entity) outside action

### ISSUE THREAD

**Issue by donpdonp** [yakyak/yakyak#1301]
ever since 1.5.11, this error is thrown about twice a day or so. the client puts up a notice about an exception being thrown, then it continues to work normally.

```
Error on YakYak window:
 {
  msg: 'Uncaught Error: Rejected (update:entity) outside action',
  url: '/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js',
  lineNo: 28,
  columnNo: 7,
  error: Error: Rejected (update:entity) outside action
      at updated (/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js:28:13)
      at Object.updatePresence (/usr/lib/yakyak/resources/app.asar/ui/models/entity.js:167:18)
      at /usr/lib/yakyak/resources/app.asar/ui/dispatcher.js:281:19
      at g (/usr/lib/yakyak/resources/app.asar/ui/util.js:173:15)
      at /usr/lib/yakyak/resources/app.asar/ui/util.js:179:18
} 
--- End of error message in YakYak window.
```

**Comment by donpdonp** [comment]
I'm watching the client log and the error seems to be part of a cycle that corresponds with loss of network. Here is more of the log.

```
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-01-07 10:56:46 INFO fetchPvt failed ENOTFOUND
connect_failed Error: getaddrinfo ENOTFOUND talkgadget.google.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'talkgadget.google.com'
}
error connecting Error: getaddrinfo ENOTFOUND talkgadget.google.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'talkgadget.google.com'
}
connected 0
connected 1
connected 2
reconnecting 3
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
hangupsjs:: disconnect
syncrecentconversations: Asking hangouts to sync recent conversations
Error on YakYak window:
 {
  msg: 'Uncaught Error: Rejected (update:entity) outside action',
  url: '/usr/lib/yakyak/resources/app.asar/node_modules/trifl/lib/action.js',
  lineNo: 28,
```

**Comment by HomerSp** [comment]
This should be fixed in the 1.5.12 beta.
