### ISSUE TITLE
New message issue (Debian)

### ISSUE THREAD

**Issue by hupmake** [yakyak/yakyak#1303]
This happens when I try to start a new conversation. No available contacts are showing up in the populated list.

Here is the output from command-line:

```
Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 {
  msg: "Uncaught TypeError: Cannot read property 'id' of undefined",
  url: 'file:///usr/lib/yakyak/resources/app.asar/ui/app.js',
  lineNo: 242,
  columnNo: 27,
  error: TypeError: Cannot read property 'id' of undefined
      at file:///usr/lib/yakyak/resources/app.asar/ui/app.js:242:27
      at EventEmitter.<anonymous> (file:///usr/lib/yakyak/resources/app.asar/ui/app.js:104:16)
      at EventEmitter.emit (events.js:315:20)
      at Object.onMessage (electron/js2c/renderer_init.js:91:925)
} 
--- End of error message in YakYak window.
```

And a screenshot (blurred for privacy):
![yakyak_shot1_blur](https://user-images.githubusercontent.com/53275084/104632099-3542ed00-566b-11eb-87b2-6e79ee197303.png)

**Comment by HomerSp** [comment]
This should now be working properly in the latest beta release!

**Comment by hupmake** [comment]
Confirmed this is working in the current 1.5.12-beta release!
