### ISSUE TITLE
fetchPvt failed Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by bishopdynamics** [yakyak/yakyak#1318]
platform: macOS 11.2.3 (x86_64)
app version: 1.5.12-beta
Date first noticed: March 30, 2021

When I run the latest prebuilt binary, I get the "Connecting" animation forever.
Here's what I get when I clone from git (c08615f):

```
$ npm run electron app

> yakyak@1.5.12-beta electron
> electron "app"

Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-01 9:26:06 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/user/projects/yakyak/app/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/Users/user/projects/yakyak/app/node_modules/q/q.js:854:54)
    at /Users/user/projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/user/projects/yakyak/app/node_modules/q/q.js:816:13)
    at /Users/user/projects/yakyak/app/node_modules/q/q.js:624:44
    at runSingle (/Users/user/projects/yakyak/app/node_modules/q/q.js:137:13)
    at flush (/Users/user/projects/yakyak/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/user/projects/yakyak/app/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/Users/user/projects/yakyak/app/node_modules/q/q.js:854:54)
    at /Users/user/projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/user/projects/yakyak/app/node_modules/q/q.js:816:13)
    at /Users/user/projects/yakyak/app/node_modules/q/q.js:624:44
    at runSingle (/Users/user/projects/yakyak/app/node_modules/q/q.js:137:13)
    at flush (/Users/user/projects/yakyak/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
reconnecting 0
```

and it continues with reconnecting over and over.

**Comment by PinkFreud** [comment]
Same error with 1.5.11 on Debian: fetchPvt failed Unexpected token < in JSON at position 0, followed by a never-ending connecting loop.

**Comment by baloghadamsoftware** [comment]
Same here, in all versions I tried this far: 1.5.10, 1.5.11 and 1.5.12-beta. System is Ubuntu 20.04.

**Comment by rgcosma** [comment]
something must have changed in the Google auth dialogue, deleting YakYak's settings (`~/Library/Application Support/yakyak` for me) solved this

**Comment by bsundsrud** [comment]
> something must have changed in the Google auth dialogue, deleting YakYak's settings (~/Library/Application Support/yakyak for me) solved this

This did not work for me on Linux.  Deleted `~/.config/yakyak` and relaunched. Got the login email/password screen as expected, but then got stuck at the connecting screen again.

Ubuntu 18.04, yakyak 1.5.11.

Some more output:
```
Starting Yakyak v1.5.11...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
(node:3521) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

login: did-finish-load https://accounts.google.com/ServiceLogin?...
login: programmatic auth
login: did-finish-load https://accounts.google.com/signin/challenge/pwd/1?...
login: did-finish-load https://accounts.google.com/o/oauth2/programmatic_auth?...
login: programmatic auth
2021-04-06 15:11:07 WARN no SAPISID cookie
2021-04-06 15:11:07 WARN no SAPISID cookie
2021-04-06 15:11:07 WARN no SAPISID cookie
2021-04-06 15:11:07 WARN no SAPISID cookie
2021-04-06 15:11:09 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by HomerSp** [comment]
Google have removed the page that's used to fetch the private token that's required to properly use yakyak (https://hangouts.google.com/talkgadget/_/extension-start). I'm currently looking at trying to fix this.

**Comment by HomerSp** [comment]
This should be fixed now, so please try the latest v1.5.12-beta or v1.5.11.1 builds and let me know your results.

**Comment by joecoolio** [comment]
1.5.11.1 resolved the issue!

**Comment by PinkFreud** [comment]
1.5.11.1 works here too.  Thanks!

**Comment by bsundsrud** [comment]
1.5.11.1 works for me as well.  Thanks!
