### ISSUE TITLE
YakYak Stuck at Connecting 

### ISSUE THREAD

**Issue by Wasca** [yakyak/yakyak#1319]
Is anyone else having issues at the startup of YakYak with connecting? This is what I'm seeing, and it does not go past this.

I'm on MacOS HighSierra 10.13.6

![image](https://user-images.githubusercontent.com/869112/113788143-b9df6c00-977f-11eb-8838-704b5408fbce.png)

I've tried Beta 1.5.12, but it does the same.

**Comment by dguttierrez** [comment]
I have the same issue on MacOS Big Sur and on Windows 10. Didn't test Linux. Version is 1.5.11.

**Comment by Neo2SHYAlien** [comment]
Same issue with Linux. Version is 1.5.11 and 1.5.12beta. Probably google change something
[yayak.log](https://github.com/yakyak/yakyak/files/6269159/yayak.log)

**Comment by cwonrails** [comment]
Same issue on MacOS Big Sur 11.2.3.

**Comment by mengland80** [comment]
Looks like something at google is returning markup rather than JSON:

Starting Yakyak v1.5.11...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-07 15:38:22 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by zackotronic** [comment]
any idea of a fix?

**Comment by icemocha4my** [comment]
I have the same issue with 1.5.11 and 1.5.12 beta 

I am using Windows 10 Pro version 20H2

**Comment by stotes** [comment]
I have the same issue with 1.5.11 and 1.5.12 beta Win10

**Comment by EndaerPatt** [comment]
The same issue. since this morning
![Przechwytywanie](https://user-images.githubusercontent.com/67026480/113978844-bf52ba00-9844-11eb-8e32-ac072cf71eb0.PNG)

**Comment by consummo** [comment]
I'm having the same issue on Ubuntu 20.04. Both the snap install and freshly installed deb package (1.5.9) get stuck during connect. From the console I see a `Unexpected Token < in JSON at position 0` error. After that the connect loop seems to start over.

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-08 10:14:34 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/channel.js:88:23
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/channel.js:88:23
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

**Comment by lipoja** [comment]
Same happen to me. Running on Fedora 33.

```
Starting Yakyak v1.5.11...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-08 10:15:01 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-08 10:15:05 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
reconnecting 0
```

**Comment by AsgrimS** [comment]
I have the same issue with 1.5.11 and 1.5.12 beta
Using Ubuntu 20.04

**Comment by cwonrails** [comment]
@HomerSp identified the issue in this issue: https://github.com/yakyak/yakyak/issues/1318#issuecomment-815626030

**Comment by HomerSp** [comment]
This should be fixed now, so please try the latest v1.5.12-beta or v1.5.11.1 builds and let me know your results.

**Comment by dguttierrez** [comment]
Hello

Tnx. It works on MacOS BigSur and on Windows 10.

On Debian 10 Testing I get this error:

reconnecting 0
resolving proxy http://plus.google.com <http://plus.google.com/>
resolving proxy https://plus.google.com <https://plus.google.com/>
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-08 15:46:25 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:69:19
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:570:49
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Regards,

— Davor

**Comment by jeffgaynorspok** [comment]
@HomerSp Hotfix resolved the issue for me. Thanks!

**Comment by mfcallahan** [comment]
> This should be fixed now, so please try the latest v1.5.12-beta or v1.5.11.1 builds and let me know your results.

Thanks for the quick fix! v1.5.11.1 on Linux Mint 20.1 has resolved the "Connecting..." issue for me.

**Comment by averissimo** [comment]
Great work @HomerSp

**Comment by Neo2SHYAlien** [comment]
@HomerSp latest beta working fine for me. Thanks!

**Comment by icemocha4my** [comment]
@HomerSp Thanks for the quick fix! v1.5.11.1 on Windows 10 v20H2 works!!

**Comment by lipoja** [comment]
Fixed for me, thank you @HomerSp

**Comment by Wasca** [comment]
@HomerSp Thanks buddy, v1.5.11.1 has fixed my original issue.
