### ISSUE TITLE
Yakyak fails to launch, creates multiple processes

### ISSUE THREAD

**Issue by SOL4RIS** [yakyak/yakyak#1325]
Issue began at some point yesterday morning. Yakyak (1.5.11) was unable to connect, so I closed the app to try restarting it. Double-clicking on the executable would not bring up the app; however, multiple processes for Yakyak would appear in the task manager.

![2021-0409-123127-Window](https://user-images.githubusercontent.com/79487317/114225532-aa9f2080-992f-11eb-986d-be8f02e2ddab.png)

I attempted this morning to update to the latest hotfix (1.5.11.1) and have the same issue.  I am running Windows 10 (version info below).

![2021-0409-123059-Window](https://user-images.githubusercontent.com/79487317/114225533-ab37b700-992f-11eb-83f0-fe98cefe39c8.png)

**Comment by HomerSp** [comment]
I'm assuming you closed all running yakyak instances before trying to start it? If you run yakyak from a terminal or command prompt it should give more info on what's going on.

**Comment by SOL4RIS** [comment]
> I'm assuming you closed all running yakyak instances before trying to start it? If you run yakyak from a terminal or command prompt it should give more info on what's going on.

Correct, I killed all processes before attempting to start the app again.  Trying to launch from command prompt, it seems to get stuck in a loop erroring out on two images:

![2021-0411-135807-Clipboard](https://user-images.githubusercontent.com/79487317/114319320-30f16900-9ace-11eb-9e95-7cca3cd24458.png)

This of course is on the PC side.  I didn't attempt the same with my Mac, but the Mac also will not load Yakyak.

**Comment by MrSilco** [comment]
I have the same symptoms but with different error on Mac:

> Starting Yakyak v1.5.11...
>   using hangupsjs v1.3.10
> --------
> hangupsjs:: connecting
> reconnecting 0
> resolving proxy http://plus.google.com
> resolving proxy https://plus.google.com
> resolved proxy DIRECT
> resolved proxy DIRECT
> 2021-04-12 9:51:50 INFO fetchPvt failed Unexpected token < in JSON at position 0
> connect_failed SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
>     at _fulfilled (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:854:54)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:883:30
>     at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:816:13)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:624:44
>     at runSingle (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:137:13)
>     at flush (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:125:13)
>     at processTicksAndRejections (internal/process/task_queues.js:79:11)
> error connecting SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
>     at _fulfilled (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:854:54)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:883:30
>     at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:816:13)
>     at /Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:624:44
>     at runSingle (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:137:13)
>     at flush (/Applications/YakYak.app/Contents/Resources/app.asar/node_modules/q/q.js:125:13)
>     at processTicksAndRejections (internal/process/task_queues.js:79:11)
> reconnecting 0
> resolving proxy http://plus.google.com
> resolving proxy https://plus.google.com
> resolved proxy DIRECT
> resolved proxy DIRECT
> ...
>

**Comment by HomerSp** [comment]
@SOL4RIS Is this on a clean install, or an upgrade? I've released an update (v1.5.11.2) that fixes an issue when you do an upgrade, but this looks slightly different from that. Could you try the v1.5.11.2 release anyway? And if that doesn't work, try doing a clean install. The log output is a bit weird, because it says it's trying to load the icons from the app.asar file, but the icons are actually in the app.asar.unpacked directory. Not sure why it's doing that.

@MrSilco That's a different issue that was fixed in v1.5.11.1.

**Comment by laurielounge** [comment]
v1.5.11.2 fixed the connection issue for me. Great work.
Fedora 33 x64

**Comment by freimair** [comment]
I am facing the same issue as @MrSilco 

<details>

```
% yakyak
Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-13 9:54:44 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/share/yakyak-git/resources/app/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:854:54)
    at /usr/share/yakyak-git/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:816:13)
    at /usr/share/yakyak-git/resources/app/node_modules/q/q.js:624:44
    at runSingle (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:137:13)
    at flush (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/share/yakyak-git/resources/app/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:854:54)
    at /usr/share/yakyak-git/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:816:13)
    at /usr/share/yakyak-git/resources/app/node_modules/q/q.js:624:44
    at runSingle (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:137:13)
    at flush (/usr/share/yakyak-git/resources/app/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Running on Arch linux.
</details>

The "Unexpected token" message hints at maybe a changed API? Given that plus.google.com has been retired, maybe they changed the redirect somehow. Yet again, the error seems to originate in their hangupsjs lib...

**Comment by adampatterson** [comment]
Confirmed that the latest version v1.5.11.2 works on macOS

**Comment by adampatterson** [comment]
> Confirmed that the latest version v1.5.11.2 works on macOS

Well, It worked this morning, but now it won't load.

**Comment by HomerSp** [comment]
@adampatterson Unfortunately there's not a whole lot I can do without the program output.

**Comment by adampatterson** [comment]
@HomerSp I found an inspector, the console has this:

```
DevTools failed to load SourceMap: Could not parse content for file:///Applications/YakYak.app/Contents/Resources/app.asar/node_modules/tagg/lib/tagg.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/YakYak.app/Contents/Resources/app.asar/node_modules/notr/notr.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/YakYak.app/Contents/Resources/app.asar/node_modules/fnuc/lib/fnuc.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/YakYak.app/Contents/Resources/app.asar/node_modules/uri-js/dist/es5/uri.all.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/YakYak.app/Contents/Resources/app.asar/node_modules/performance-now/lib/performance-now.js.map: Unexpected end of JSON input
```

Is there a better output that would help?

**Comment by HomerSp** [comment]
@adampatterson If you run it from a terminal or command prompt you should get more useful output. Even more so if you run it with the --debug argument (the output can contain sensitive information such as emails and phone numbers though, so feel free to remove those).

**Comment by jrohland** [comment]
I started having problems launching this morning. Running on linux and the UI loads but it gets stuck on the connecting screen. Launching via terminal show a json parse error on connection attempt:

`Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.3.10
--------

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:71:44: Invalid number for color value

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:72:44: Invalid number for color value

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:74:53: Invalid number for color value

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:75:53: Invalid number for color value

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:76:56: Invalid number for color value

(yakyak:59641): Gtk-WARNING **: 09:15:25.173: Theme parsing error: colors.css:77:65: Invalid number for color value
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-14 9:15:25 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-14 9:15:28 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

**Comment by alpenandrew** [comment]
on the beta release, I don't get a connection failure, but I do get 5 processes
