### ISSUE TITLE
connect_failed TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by laurielounge** [yakyak/yakyak#1343]
Hi there

Fedora 33 x64

Cannot connect. Installed with yakyak-1.5.11.3-linux-x64.rpm.

reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-16 12:06:24 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:69:19
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting TypeError: Cannot read property 'length' of null
    at /opt/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:69:19
    at _fulfilled (/opt/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app.asar/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by laurielounge** [comment]
Fixed with uninstall, delete /opt/yakyak, delete ~/.config/yakyak , reinstall.

**Comment by HomerSp** [comment]
What version were you on previously? I'll see if I can add some fail checks to hopefully alleviate issues like these in the future.

**Comment by laurielounge** [comment]
Hi there,

I think it was 1.5.11.2

**Comment by jeremycourtaban** [comment]
Hello,
Same bug for me this morning on v1.5.11.2 - Ubuntu 18.04.
Uninstall v1.5.11.2, ddl latest v1.5.11.4 here, install it, the bug was still here.
Checked /opt/yakyak, doesn't exist for me.
Checked and delete ~/.config/yakyak.
Reinstall v1.5.11.4.
Start Yakyak, OK it run fine.
Thanks to @laurielounge.
