### ISSUE TITLE
Unable to connect - Win10

### ISSUE THREAD

**Issue by definitelysmib** [yakyak/yakyak#1350]
A couple weeks ago, yakyak stopped being able to connect; the GUI would just sit and the "Connecting..." screen indefinitely.

I finally got around to launching via command line, and this is what I get:

`Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.3.10
--------
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-04-30 18:41:41 INFO fetchPvt failed Unexpected token < in JSON at position 0
connect_failed SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\channel.js:117:21
    at _fulfilled (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:624:44
    at runSingle (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\channel.js:117:21
    at _fulfilled (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:624:44
    at runSingle (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (C:\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

It will then keep attempting to reconnect, getting the same error every time.

I've tried deleting everything, including the folders in AppData and reinstalling, but it didn't help.

**Comment by HomerSp** [comment]
Did you try the latest beta release?

**Comment by definitelysmib** [comment]
I downloaded the 1.5.12 beta again when I tried the reinstall, which was about a week ago.

**Comment by kranix0** [comment]
I had the same error. I deleted my settings folder and logged in again. Now it works.

**Comment by HomerSp** [comment]
It looks from the output like you're still using an old version (see eg https://github.com/yakyak/yakyak/issues/1318). Please download the latest one and try again.

**Comment by definitelysmib** [comment]
Installing 1.5.11.4 has fixed it. Thank you.
I wonder if I accidentally reinstalled the older version of 1.5.12 last week instead of the freshly downloaded one...
