### ISSUE TITLE
Connection fails (since 15.06.2021)

### ISSUE THREAD

**Issue by Saur0o0n** [yakyak/yakyak#1360]
Hi,
I guess google has again broke something...
I'm getting (with YY beta) crash loop on this type:
```
Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.4.0-beta
--------
syncrecentconversations: Asking hangouts to sync recent conversations
2021-06-22 8:59:35 WARN no SAPISID cookie
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-06-22 8:59:35 WARN no SAPISID cookie
2021-06-22 8:59:36 WARN no SAPISID cookie
2021-06-22 8:59:36 WARN no SAPISID cookie
2021-06-22 8:59:36 WARN no SAPISID cookie
2021-06-22 8:59:36 WARN no SAPISID cookie
2021-06-22 8:59:36 WARN no SAPISID cookie
connect_failed Error: No auth headers
    at ChatReq.baseReq (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/chatreq.js:33:25)
    at ChatReq.req (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/chatreq.js:77:19)
    at Client.initrecentconversations (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/client.js:613:27)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/client.js:157:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
error connecting Error: No auth headers
    at ChatReq.baseReq (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/chatreq.js:33:25)
    at ChatReq.req (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/chatreq.js:77:19)
    at Client.initrecentconversations (/usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/client.js:613:27)
    at /usr/lib/yakyak/resources/app.asar/node_modules/hangupsjs/lib/client.js:157:21
    at _fulfilled (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
    at /usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
    at flush (/usr/lib/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
reconnecting 0
```
It started around 15.06.

**Comment by Saur0o0n** [comment]
I see it's fixed in v1.5.11.5 - closing.
