### ISSUE TITLE
'Not connected' 'Connecting' loop on stable, 'Connecting...' forever on beta

### ISSUE THREAD

**Issue by alpenandrew** [yakyak/yakyak#1369]
In both the beta and latest stable version, yakyak cannot connect

**Comment by HomerSp** [comment]
Do you have terminal/console output? Difficult to say what would be the cause otherwise.

**Comment by alpenandrew** [comment]
> 
> 
> Do you have terminal/console output? Difficult to say what would be the cause otherwise.

**STABLE:**
Starting Yakyak v1.5.11.5...
  using hangupsjs v1.4.0-beta
--------
syncrecentconversations: Asking hangouts to sync recent conversations
2021-07-23 12:37:15 WARN no SAPISID cookie
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-07-23 12:37:15 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting TypeError: Cannot read property 'length' of null
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (c:\Users\User\Desktop\yakyakstable\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
2021-07-23 12:37:29 WARN no SAPISID cookie
2021-07-23 12:37:29 WARN no SAPISID cookie
2021-07-23 12:37:29 WARN no SAPISID cookie
2021-07-23 12:37:29 WARN no SAPISID cookie

and then it loops again from 'reconnecting 0'

**BETA**
Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.4.0-beta
--------
syncrecentconversations: Asking hangouts to sync recent conversations
2021-07-23 12:39:28 WARN no SAPISID cookie
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
2021-07-23 12:39:28 WARN no SAPISID cookie
resolved proxy DIRECT
resolved proxy DIRECT
2021-07-23 12:39:29 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error connecting TypeError: Cannot read property 'length' of null
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (c:\Users\User\Desktop\yakyak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
2021-07-23 12:39:30 WARN no SAPISID cookie
2021-07-23 12:39:30 WARN no SAPISID cookie
2021-07-23 12:39:30 WARN no SAPISID cookie
2021-07-23 12:39:30 WARN no SAPISID cookie

and then it loops again from 'reconnecting 0'

**Comment by bcontrol** [comment]
same thing. YakYak v1.5.11.4 (latest)

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-07-27 11:01:50 INFO fetchPvt failed Cannot convert undefined or null to object
connect_failed TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:434:19)
    at values (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:438:16)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/util.js:12:34
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:234:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:21:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:47:17
    at _fulfilled (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
error connecting TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:434:19)
    at values (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:438:16)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/util.js:12:34
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:234:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:21:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:47:17
    at _fulfilled (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:816:13)

```

**Comment by PinkFreud** [comment]
I'm seeing the same behavior with 1.5.11.5 on Debian.

`Starting Yakyak v1.5.11.5...
  using hangupsjs v1.4.0-beta
--------
syncrecentconversations: Asking hangouts to sync recent conversations
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-07-31 19:11:25 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
`

**Comment by PinkFreud** [comment]
Never mind.  This was resolved for me by following https://github.com/yakyak/yakyak/issues/1343 - uninstall yakyak, remove local yakyak config, reinstall.

**Comment by alpenandrew** [comment]
for us technically uninclined where is the config dir on Windows?

**Comment by PinkFreud** [comment]
> for us technically uninclined where is the config dir on Windows?

According to the source, it looks like it should be under your home dir\AppData\Local somewhere, or so it appears.

const windows = name => {
        const appData = env.LOCALAPPDATA || path.join(homedir, 'AppData', 'Local');

        return {
                // data/config/cache/log are invented by me as Windows isn't opinionated about this
                data: path.join(appData, name, 'Data'),
                config: path.join(appData, name, 'Config'),
                cache: path.join(appData, name, 'Cache'),
                log: path.join(appData, name, 'Log'),
                temp: path.join(tmpdir, name)
        };
};

**Comment by bennettscience** [comment]
I'm seeing the same on MacOS Catalina (10.15.7) installed both from the x64 package (1.5.11.5) and from homebrew. The login window doesn't come up at all, no `yakyak` directory in`/.config`.

**Comment by krtaylor7024** [comment]
Where, exactly, is this config file in Windows 11?  I did a grep in [user]\AppData\Local and found nothing remotely related to yak.  I use YakYak every day and now it is not working at all, exactly as described above; deleting the YakYak install directory and reinstalling it did nothing, presumably because the bad config file is still somewhere around.
