### ISSUE TITLE
Cannot connect - Stuck in switching between "connected" and "not connecting".

### ISSUE THREAD

**Issue by guss77** [yakyak/yakyak#1374]
Version: 1.5.11.4 installed from the snap store on Ubuntu

When running from the command line, I get this message:

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2021-08-17 21:20:16 INFO fetchPvt failed Cannot convert undefined or null to object
connect_failed TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:434:19)
    at values (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:438:16)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/util.js:12:34
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:234:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:21:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:47:17
    at _fulfilled (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
error connecting TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:434:19)
    at values (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:438:16)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/util.js:12:34
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:234:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/fnuc/lib/fnuc.js:21:18
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/hangupsjs/lib/initdataparser.js:47:17
    at _fulfilled (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
    at /snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/snap/yakyak/117/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
```

**Comment by guss77** [comment]
Installing 1.5.11.5 using the deb package solved the problem for me.

**Comment by kwrobel** [comment]
I am on 1.5.11.5 on MacOS Big Sur and it's doing that for me. "Connecting" for like a split second, then "Not connected". Is the developer aware of this issue?
