### ISSUE TITLE
Connecting not connecting Win 10

### ISSUE THREAD

**Issue by TheOmegaPope** [yakyak/yakyak#1398]
Not sure if this project is still live as I haven't seen an update in some time.

If it is though I would love to get a patch to fix a constant Connecting issue I have with my deployment. I had the latest stable release and it had the issue and after going through other Issue posts I couldn't make sense of where files users referred to on other platforms were on Windows, either to clear or look at. The wild guesses at locations didn't exist.

Prior to this year before my winter holidays YakYak was connecting fine and had no issues however when I got back to work Jan 1st it has  not connected since. No real updates have happened to my system so if there are any ideas on how to fix this issue or if this is common with a change to google recently and an update is coming, it would be appreciated.

**Comment by HomerSp** [comment]
It's being passively worked on - as in, I fix things as I spot them, that's why there can be months between commits.

Could you open yakyak from cmd and post the output here? It should say what's wrong.

They probably talked about the local data folder, which is %APPDATA%/yakyak on Windows. You could try removing that which should force a fresh install, asking you to log in again next time you open yakyak.

**Comment by TheOmegaPope** [comment]
Here is the CMD output:

`Starting Yakyak v1.5.12-beta...
  using hangupsjs v1.4.0-beta
--------
syncrecentconversations: Asking hangouts to sync recent conversations
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2022-01-19 7:36:54 INFO fetchPvt failed Cannot read property 'length' of null
connect_failed TypeError: Cannot read property 'length' of null
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error connecting TypeError: Cannot read property 'length' of null
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\hangupsjs\lib\initdataparser.js:69:19
    at _fulfilled (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:854:54)
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:816:13)
    at C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:570:49
    at runSingle (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:137:13)
    at flush (C:\Users\cpnorman\Downloads\Software\YakYak-win32-x64\resources\app.asar\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
reconnecting 0`

I will try the fresh install

**Comment by TheOmegaPope** [comment]
So the fresh install solved the issue, no idea what got caught up after all that time but relogging in worked fine.
