### ISSUE TITLE
Can only run once

### ISSUE THREAD

**Issue by RayFoss** [yakyak/yakyak#157]
I log in with my domain account. Everything works well... then I close it. When I try to open it again it says connecting, and crashes.

```
YakYak local version is 1.1.3, released version is 1.1.3
/home/amama/opt/yakyak/resources/app/ui/views/input.js:110 Why is this running multiple times?
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for people
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for nature
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for food
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for activity
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for travel-places
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for objects
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for symbols
/home/amama/opt/yakyak/resources/app/ui/views/input.js:115 Creating selector for flags
/home/amama/opt/yakyak/resources/atom.asar/renderer/api/lib/remote.js:109 Uncaught Error: Cannot read property 'position' of undefined
TypeError: Cannot read property 'position' of undefined
    at Function.Menu.buildFromTemplate (/home/amama/opt/yakyak/resources/atom.asar/browser/api/lib/menu.js:291:15)
    at callFunction (/home/amama/opt/yakyak/resources/atom.asar/browser/lib/rpc-server.js:148:18)
    at EventEmitter.<anonymous> (/home/amama/opt/yakyak/resources/atom.asar/browser/lib/rpc-server.js:234:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/home/amama/opt/yakyak/resources/atom.asar/browser/api/lib/web-contents.js:97:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

UPDATE: Seems like somethings also up with the keep alive. This happens repeatedly on first run (while it's working)
```

/home/amama/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:40 Uncaught Error: Rejected (alive) during action: move
```

**Comment by RayFoss** [comment]
Duplicate of #130 and #136 which was patched with a0aa0cee05727cbe7204964f983e1074fe378ce6 and merged to master. Should be released with 1.1.4.
