### ISSUE TITLE
Dont start in ubuntu 14.04

### ISSUE THREAD

**Issue by rquevedo** [yakyak/yakyak#184]
I download the package "". Run app from terminal and this errors show. Multiples windows apear whit no end.

reisy@Aspire:~/Escritorio/linux-x64$ ./yakyak 
hconnect
asking for login credentials
2016-06-07 11:47:14 ERROR getAuth failed TypeError: mainWindow.loadUrl is not a function
    at /home/reisy/Escritorio/linux-x64/resources/app/login.js:25:25
    at Function.promise (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:682:9)
    at module.exports (/home/reisy/Escritorio/linux-x64/resources/app/login.js:9:14)
    at Auth.creds (/home/reisy/Escritorio/linux-x64/resources/app/main.js:176:14)
    at /home/reisy/Escritorio/linux-x64/resources/app/node_modules/hangupsjs/lib/auth.js:125:24
    at _fulfilled (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:796:13)
    at /home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:857:14
    at runSingle (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:137:13)
connect_failed
error connecting TypeError: mainWindow.loadUrl is not a function
    at /home/reisy/Escritorio/linux-x64/resources/app/login.js:25:25
    at Function.promise (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:682:9)
    at module.exports (/home/reisy/Escritorio/linux-x64/resources/app/login.js:9:14)
    at Auth.creds (/home/reisy/Escritorio/linux-x64/resources/app/main.js:176:14)
    at /home/reisy/Escritorio/linux-x64/resources/app/node_modules/hangupsjs/lib/auth.js:125:24
    at _fulfilled (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:796:13)
    at /home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:857:14
    at runSingle (/home/reisy/Escritorio/linux-x64/resources/app/node_modules/q/q.js:137:13)
asking for login credentials

**Comment by albertsj1** [comment]
I just downloaded the osx release of 1.2.1 here on github.  When I ran it, it popped up an empty window.  Same thing on relaunch.  So, I figured I'd clone the repo, build it and run at the command line.  I got the exact same error messages as above.

**Comment by ctcpip** [comment]
+1

**Comment by davibe** [comment]
Sorry. expect this to be fixed in 1.2.2 which i am uploading (it's going to take a while i am on a slow connection). Have a look at #185
