### ISSUE TITLE
error on install - "node not found", "weird error 127"?

### ISSUE THREAD

**Issue by ghost** [yakyak/yakyak#200]
I was attempting to follow the setup instructions, however, I run into trouble at the last step "gulp" .
I am running on elementary OS 0.3.2. Freya (64-bit).

I have the following output:

```
> electron-prebuilt@0.37.4 postinstall /home/sahan/Git/yakyak/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 200 https://registry.npmjs.org/ansicolors/-/ansicolors-0.2.1.tgz
npm ERR! weird error 127
/bin/sh: 1: node: not found
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! configure error 
gypgyp  ERR! ERR! stackstack Error: `gyp` failed with exit code: 1
 Error: `gyp` failed with exit code: 1
gyp ERR!gyp  stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
ERR! gypstack      at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
ERR!gyp  ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-59-generic
gyp gypERR!  command "nodejs" "/usr/bin/node-gyp" "rebuild"
ERR! gyp ERR!System Linux 3.19.0-59-generic
 gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sahan/Git/yakyak/node_modules/gulp-auto-reload/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
cwd /home/sahan/Git/yakyak/node_modules/gulp-auto-reload/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 200 https://registry.npmjs.org/colors/-/colors-1.0.3.tgz
npm http 200 https://registry.npmjs.org/redeyed/-/redeyed-0.5.0.tgz
npm ERR! Error: ENOENT, lstat '/home/sahan/tmp/npm-3690-uB_vfCIT/1465747025734-0.9312694482505322/package/replace.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-59-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/sahan/Git/yakyak
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/sahan/tmp/npm-3690-uB_vfCIT/1465747025734-0.9312694482505322/package/replace.js
npm ERR! fstream_path /home/sahan/tmp/npm-3690-uB_vfCIT/1465747025734-0.9312694482505322/package/replace.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/sahan/tmp/npm-3690-uB_vfCIT/1465747032385-0.40270885406062007/package
npm ERR! addLocalDirectory Could not pack "/home/sahan/tmp/npm-3690-uB_vfCIT/1465747032385-0.40270885406062007/package" to "/home/sahan/.npm/ansicolors/0.2.1/package.tgz"
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sahan/Git/yakyak/npm-debug.log
npm ERR! not ok code 0


```

**Comment by randymorris** [comment]
It looks to me like it's trying to run the `node` binary, which is probably `nodejs` on elementaryOS.  Try adding a symlink `node` -> `nodejs` somewhere in your path.

**Comment by davibe** [comment]
yea that's an ubuntu thing..

**Comment by averissimo** [comment]
hey! what do you have against ubuntu ;)

@ScorchingBonzai have you been able to build yakyak?

I've been using nvm for managing node versions and it is pretty cool

**Comment by DarkAxi0m** [comment]
not sure if it helps but i'm on Ubuntu  and I had to run 
> sudo apt install nodejs-legacy
to get

**Comment by DarkAxi0m** [comment]
not sure if it helps but I’m on Ubuntu  and I had to install  nodejs-legacy to get  `npm install `and `npm run gulp` to finish successfully. 

> sudo apt install nodejs-legacy


Git Tag, v1.4.1
node v4.2.6
Ubuntu 16.04.1 LTS

**Comment by averissimo** [comment]
been using Node v6.9.1 without any problems

@DarkAxi0m what was the previous version of Node you were using?
