### ISSUE TITLE
Hangup on Ubuntu 15.10

### ISSUE THREAD

**Issue by NewbiZ** [yakyak/yakyak#227]
The app loads, asks for credential, and then hangsup.

```
$ ./yakyak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
error connecting { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
```

System information:
- No http proxy used
- Ubuntu 15.10

**Comment by averissimo** [comment]
does it continue to happen?

does it happen all the time or just once in a while?

**Comment by averissimo** [comment]
@NewbiZ does not seem like a bug, but a connection problem instead

I've seen that once in a while and it seems that yakyak recovers well

**Comment by averissimo** [comment]
closing as this is sometimes a problem with connection, others it is a strange bug #449
