### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ricanon** [yakyak/yakyak#309]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'getSize' of null
    at BrowserWindow.<anonymous> (C:\Program Files\yakyak-win32-x64\resources\app\main.js:239:42)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)

[OK]

**Comment by averissimo** [comment]
does this exception still appears in newer releases of yakyak?

please test it on 1.4.0-beta3 and report it again

see #451 for the download link
