### ISSUE TITLE
unable to run deploy.sh on windows 10

### ISSUE THREAD

**Issue by oasisfleeting** [yakyak/yakyak#339]
tried from both cmd and cygwin with admin rights. 

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\admin>cat L:\Documents\GitHub\yakyak\npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle yakyak@1.3.1~predeploy: yakyak@1.3.1
6 silly lifecycle yakyak@1.3.1~predeploy: no script for predeploy, continuing
7 info lifecycle yakyak@1.3.1~deploy: yakyak@1.3.1
8 verbose lifecycle yakyak@1.3.1~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle yakyak@1.3.1~deploy: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;L:\Documents\GitHub\yakyak\node_modules\.bin;C:\Program Files\nodejs;L:\Mobaxterm\slash\bin;L:\Mobaxterm\slash\bin;C:\WINDOWS;C:\WINDOWS\system32;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\ffmpeg\bin;C:\Program Files\Amazon\AWSCLI;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files\Git\cmd;C:\Program Files (x86)\WinMerge;L:\xampp\php;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Android\android-sdk;C:\Program Files (x86)\AnonVPN\bin;C:\Program Files (x86)\Google\google_appengine;C:\Users\admin\AppData\Local\atom\bin;C:\Users\admin\AppData\Roaming\npm
10 verbose lifecycle yakyak@1.3.1~deploy: CWD: L:\Documents\GitHub\yakyak
11 silly lifecycle yakyak@1.3.1~deploy: Args: [ '/d /s /c', 'bash ./deploy.sh' ]
12 silly lifecycle yakyak@1.3.1~deploy: Returned: code: 2  signal: null
13 info lifecycle yakyak@1.3.1~deploy: Failed to exec deploy script
14 verbose stack Error: yakyak@1.3.1 deploy: `bash ./deploy.sh`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid yakyak@1.3.1
16 verbose cwd L:\Documents\GitHub\yakyak
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error yakyak@1.3.1 deploy: `bash ./deploy.sh`
22 error Exit status 2
23 error Failed at the yakyak@1.3.1 deploy script 'bash ./deploy.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the yakyak package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     bash ./deploy.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs yakyak
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls yakyak
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by davibe** [comment]
It works on osx which is what i use to generate final packages.

**Comment by averissimo** [comment]
It also works in Linux/Ubuntu

Try to run deploy.sh directly

    bash ./deploy.sh --help

and (replace --all for a specific architecture if you'd like)

    bash ./deploy.sh --all

Which errors appear?

**Comment by averissimo** [comment]
@oasisfleeting deploy should run without problems in Windows environment.

No more bash dependencies :)
