### ISSUE TITLE
Uncaught exception while send new message

### ISSUE THREAD

**Issue by VincentSurelle** [yakyak/yakyak#447]
The following exception has been throwed just after I sent a message : 

`Uncaught Exception:
SyntaxError: Unexpected token 
 in JSON at position 1311
    at Object.parse (native)
    at PushDataParser.module.exports.PushDataParser.parse (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/lib/pushdataparser.js:43:21)
    at Request.<anonymous> (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/lib/channel.js:275:32)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Applications/Yakyak.app/Contents/Resources/app/node_modules/request/request.js:962:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at IncomingMessage.Readable.push (_stream_readable.js:130:10)`

I'm on OSX El Capitan.

**Comment by averissimo** [comment]
what type of message did you send?

does this happen often?

version of Yakyak?

**Comment by averissimo** [comment]
@VincentSurelle 

what type of message did you send?

does this happen often?

version of Yakyak?

**Comment by averissimo** [comment]
closing for lack of feedback.. please reopen it if you are still experiencing this
