### ISSUE TITLE
Application crash on startup (MacOS)

### ISSUE THREAD

**Issue by chrisbudden** [yakyak/yakyak#625]
I had an issue occur with my Mac last week where when I resumed from sleep, my system clock had advanced to the year 2040. Once I set it back to sync with network time (I don't know why it happened nor has it happened again), Yakyak failed to open and showed the following error.

`Uncaught Exception:
SyntaxError: Unexpected string in JSON at position 696
    at loadFromFile (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/main.js:48:12)
    at Object.<anonymous> (/private/var/folders/hp/t1cj7pr90j50x_ybph8679840000gn/T/AppTranslocation/58B36E96-127D-4CFC-A149-90519987DCBC/d/YakYak.app/Contents/Resources/app/main.js:515:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)`

I have tried reinstalling the app but it hasn't help. I also have tried to find any residual configuration for Yakyak so that I can delete it but haven't had any luck.

I am using the version from Homebrew, 1.4.1.

**Comment by chrisbudden** [comment]
To follow up - 

I have deleted the folder /Users/USERNAME/Library/Application Support/yakyak and re-started the application which let me login again.

I have the old folder in its previous state if its of any interest for debugging.

**Comment by averissimo** [comment]
wow this is some crazy stuff. @davibe macos is your thing 😛

**Comment by davibe** [comment]
The cookiestore file was corrupted. No idea how it got corrupted. @chrisbudden it's very strange that your mac clock changed like that. Something may be wrong in your mac

**Comment by gordoncasey** [comment]
@chrisbudden, exact same error here. Not sure, but could 10.12.4 Public Beta 6, upgrading to 7 to fix (fingers crossed). @davibe, do you have a workaround or steps to resolve?

**Comment by davibe** [comment]
no
