### ISSUE TITLE
Yakyak crashed on Ubuntu 16.10

### ISSUE THREAD

**Issue by jwhipp** [yakyak/yakyak#647]
As of this morning, YakYak won't start up.  My system was updated this morning, package list is below.  Since nothing else has changed, I have to assume that one of these updates caused the issue.

YakYak Error:

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token � in JSON at position 0
    at loadFromFile (/usr/share/yakyak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/usr/share/yakyak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/usr/share/yakyak/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/usr/share/yakyak/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/usr/share/yakyak/resources/app/main.js:48:12)
    at Object.<anonymous> (/usr/share/yakyak/resources/app/main.js:515:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

Package updates ran this morning:

Upgrade: update-manager-core:amd64 (1:16.10.8, 1:16.10.9), update-notifier-common:amd64 (3.175.1, 3.175.2), grub-common:amd64 (2.02~beta2-36ubuntu11, 2.02~beta2-36ubuntu11.2), update-manager:amd64 (1:16.10.8, 1:16.10.9), python3-aptdaemon.gtk3widgets:amd64 (1.1.1+bzr982-0ubuntu16, 1.1.1+bzr982-0ubuntu16.2), grub2-common:amd64 (2.02~beta2-36ubuntu11, 2.02~beta2-36ubuntu11.2), grub-pc:amd64 (2.02~beta2-36ubuntu11, 2.02~beta2-36ubuntu11.2), grub-pc-bin:amd64 (2.02~beta2-36ubuntu11, 2.02~beta2-36ubuntu11.2), python3-update-manager:amd64 (1:16.10.8, 1:16.10.9), chromium-codecs-ffmpeg-extra:amd64 (56.0.2924.76-0ubuntu0.16.10.1335, 57.0.2987.98-0ubuntu0.16.10.1344), aptdaemon-data:amd64 (1.1.1+bzr982-0ubuntu16, 1.1.1+bzr982-0ubuntu16.2), python3-aptdaemon:amd64 (1.1.1+bzr982-0ubuntu16, 1.1.1+bzr982-0ubuntu16.2), pciutils:amd64 (1:3.3.1-1.1ubuntu4, 1:3.3.1-1.1ubuntu4.1), aptdaemon:amd64 (1.1.1+bzr982-0ubuntu16, 1.1.1+bzr982-0ubuntu16.2), libpci3:amd64 (1:3.3.1-1.1ubuntu4, 1:3.3.1-1.1ubuntu4.1), update-notifier:amd64 (3.175.1, 3.175.2)
End-Date: 2017-04-10  09:19:48

**Comment by jwhipp** [comment]
Right as I posted that, I looked closer at the error and it turns out some chrome extensions were also acting  like they were "corrupted".   Looks like I have a hard drive issue.
