### ISSUE TITLE
Authorization loop?

### ISSUE THREAD

**Issue by eawtrey** [yakyak/yakyak#701]
I'm loading up YakYak for the first time on a new laptop (Windows 10), and after entering my password and my 2FA code, I get stuck in a loop where I have the "Connecting" screen, and then a brief flash on the main UI before shifting back to the separate "Connecting" screen.  

I've installed this on a different win8 machine, so I'm pretty sure this isn't account related.  I've tried deleting the AppData/Roaming directory for YakYak, but no change in behavior.

Any ideas?

**Comment by eawtrey** [comment]
To add to this, I ran it from the command prompt and saw this after entering my password:

2017-06-10 21:25:56 WARN no SAPISID cookie
2017-06-10 21:25:56 WARN no SAPISID cookie
2017-06-10 21:25:56 WARN no SAPISID cookie
2017-06-10 21:25:56 WARN no SAPISID cookie
2017-06-10 21:25:56 ERROR getAuth failed { Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
connect_failed { Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
error connecting { Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

**Comment by eawtrey** [comment]
Never mind--I think this is due to a piece of proxy software that I am running that does not allow the certificate to verify.

**Comment by averissimo** [comment]
@eawtrey that is something we have to address :\

There's already an open issue (not sure the number) about this, I'm closing the issue.

**Comment by averissimo** [comment]
and i'm sorry it took so long for you to get a response on this :)
