### ISSUE TITLE
Not loading on Linux Mint 18.2

### ISSUE THREAD

**Issue by Sovkhoz** [yakyak/yakyak#736]
I'm using yakyak version 1.4.3. It has been working flawlessly for a week and a half, then suddenly stopped launching when I boot up my laptop. Manual double clicking also won't launch the program.

There are two instances of yakyak in the system monitor. one process name is just yakyak, the second is yakyak --type=zygote --no-sandbox

here is the output of ./yakyak

==================

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token Z in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/home/sov/Documents/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/home/sov/Documents/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/home/sov/Documents/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/home/sov/Documents/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/home/sov/Documents/yakyak-linux-x64/resources/app/main.js:48:12)
    at Object.<anonymous> (/home/sov/Documents/yakyak-linux-x64/resources/app/main.js:523:4)
    at Object.<anonymous> (/home/sov/Documents/yakyak-linux-x64/resources/app/main.js:527:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

=================

**Comment by PMiner** [comment]
Possibly related to #735 ?

**Comment by arcooke** [comment]
Just got the same issue on Ubuntu MATE, with yakyak 1.4.3

```
<me>@VBUM7102:~/yakyak-linux-x64$ ./yakyak 
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token 
                               in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/home/<me>/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/home/<me>/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/home/<me>/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/home/<me>/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:48:12)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:523:4)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:527:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```
