### ISSUE TITLE
JS Error on startup

### ISSUE THREAD

**Issue by GuiAmPm** [yakyak/yakyak#870]
When I start YakYak on windows 10 x64, a borderless windows saying "An error has occured" shows up, on the js console this error is logged (I'm actually using version 1.5.0, ignore the folder name):

Uncaught Error: Cannot find module 'ip-regex'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\yakyak-1.4.4-win32-x64\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\yakyak-1.4.4-win32-x64\resources\app\node_modules\uber-url-regex\index.js:2:17)
    at Object.<anonymous> (C:\yakyak-1.4.4-win32-x64\resources\app\node_modules\uber-url-regex\index.js:31:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Edit:** I think it's related to #869

**Comment by andromedastudios1** [comment]
Might want to close this issue.
