### ISSUE TITLE
linux stops at "connecting"

### ISSUE THREAD

**Issue by raoel** [yakyak/yakyak#895]
Hello there,

```
> uname -a 
Linux raoel 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux
```

```
> lsb_release -a 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster
```

(debian testing)

clean install from official binary release called `yakyak-1.4.3-linux-x64.tar.gz`

I enter username / password / 2-FA and then I get a "connecting" screen and nothing happens.
This is what happens in my console:

```
> /opt/yakyak-linux-x64/yakyak 
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
```

**Comment by abarragan** [comment]
Same here, exactly the same output when running on CL. Debian 9. Any update on this if this is acknowledge or smth? Thanks.

**Comment by smartm0use** [comment]
Sam here too. I'm on corporate proxy and YakYak stucks on connecting loop.
I tried both latest version (1.5.3) and precompiled binary (version 1.5.0.)

**Comment by juhasim** [comment]
I also have the same problem, with both yakyak 1.4.3 and 1.5.3
This started occurring today. `connect_failed SyntaxError: Unexpected token <`

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
reconnecting 0
```

**Comment by smartm0use** [comment]
I think your issue is different. I get the same error today, even connecting with another computer without proxy.

**Comment by juhasim** [comment]
Ok.
I created my own issue: https://github.com/yakyak/yakyak/issues/919
Hope these get fixed.

**Comment by KaeMame** [comment]
Your new ticket is a dupe of #918 I think.

**Comment by robkorv** [comment]
Hi, I have the same problem on  ubuntu 14.04 node 6. Anybody know how to fix it?

I started it once, then I needed to login and after that the main windows didn't show.
Then I made a fresh clone and did:
```bash
npm install
npm run gulp
npm run electron app
```

Now the terminal shows this, but nothing else happens:
```bash
> yakyak@1.5.1 electron /home/robkorv/compound/yakyak
> electron "app"

hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
```

**Comment by robkorv** [comment]
While searching for a solution the main window just popped up and all is good now.

**Comment by laneschmidt** [comment]
Stuck on connecting on Ubuntu 16.04 LTS, installed from the Software Center directly and through Snap with the same issues. It gets stuck indefinitely on "Connecting" after logging in with Google account info.

**Comment by robkorv** [comment]
I can confirm that v1.5.3 fixes this issue :heart:.
