### ISSUE TITLE
Hangs on connecting state because of response parsing error

### ISSUE THREAD

**Issue by juhasim** [yakyak/yakyak#919]
I cannot get pass the Connecting -state.
The same problem with both yakyak 1.4.3 and 1.5.3

This started occurring today. connect_failed SyntaxError: Unexpected token <
Deleting ~/.config/yakyak/cookies.json does not solve the problem.

Ubuntu 18.04 LTS

Log output:
```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
reconnecting 0
```

**Comment by smartm0use** [comment]
The same happens here today.

**Comment by matthieumontaigu** [comment]
Same here

**Comment by sarabsilveira** [comment]
same here on mac os

**Comment by daniel-rocha-ciandt** [comment]
Same here

**Comment by KBassford** [comment]
Same ...
OS: Parrot GNU/Linux 4.0
yakyak/now 1.5.0 amd64 [installed,local]

reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Comment: Worked yesterday (2018-05-16)

**Comment by chadgeary87** [comment]
Likewise
fedora 28 [4.16.8-300.fc28.x86_64]
yakyak 1.5.0 [rpm]

$ yakyak 
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
reconnecting 0

**Comment by zcmack** [comment]
win10 as well

**Comment by lguerard** [comment]
Same error on Mint 18

**Comment by danbob** [comment]
Looks like Google added a nonce to a script tag which broke yakyak's HTML parsing. Workaround: in the file [yakyak directory]/node_modules/hangupsjs/lib/init.js, edit line 59
```javascript
html = html.replace(/<\/?script>/gm, '');
```
to
```javascript
html = html.replace(/<\/?script.*?>/gm, '');
```

**Comment by chad-mg** [comment]
Thanks danbob, that worked for me.
Fedora path for reference, /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js

**Comment by dep** [comment]
Thank @danbob 
MacOS path for reference
`/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js`

**Comment by llorllale** [comment]
@danbob thanks, it works

**Comment by cristianoronan** [comment]
Thanks @danbob It's works in macOS High Sierrra 10.13.4

/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js

html = html.replace(/<\/?script>/gm, '');
to

html = html.replace(/<\/?script.*?>/gm, '');

**Comment by KBassford** [comment]
Found mine under /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js
adding ".*?" after "script" worked as well.
Thanks for the fix.

**Comment by TheJoelGray** [comment]
The fix worked for me on my Mac, but not on my Windows 10 machine. Anyone have any luck with Windows?

**Comment by Courtney-Lang** [comment]
@TheJoelGray On Windows 10. I followed the same steps @danbob outlined, only the file is located wherever you saved the initial download (mine was still in the Downloads folder). So:
`/Downloads/yakyak-1.4.3-win32-x64/YakYak-win32-x64/resources/app/node_modules/hangupjs/lib/init.js`

**Comment by kineado** [comment]
Thanks @danbob it worked for me too.

**Comment by TheJoelGray** [comment]
Hi @Courtney-Lang, I did find the file, I'd moved mine, unfortunately editing it per @danbob and others did not resolve the issue, it still sits on "connecting" and gives me a brief message which disappears after a few seconds reading "Possible fatal error on Main Process. Yak Yak may stop working as expected"

**Comment by kyurthich** [comment]
@TheJoelGray try deleting the folder here:

%AppData%\yakyak

Make sure the application is closed first. 
This will be like a fresh install then.

**Comment by kyurthich** [comment]
Hm. Seems odd. 
I think I am out of ideas if deleteing the whole YakYak directory in AppData didn't help.

**Comment by oliverharrison** [comment]
This worked for me. Thanks!

**Comment by DanLauer** [comment]
I've tried deleting the %appdata%\yakyak folder on Win 10...no joy.

**Comment by TheJoelGray** [comment]
I just deleted the yakyak AppData folder AND my install (which was the current release version 1.4.4). I then downloaded the prerelease 1.5.0 and implemented the modification mentioned above and now it's working for me.

**Comment by matthewhively** [comment]
@danbob 
Your fix worked for me as well.

**Comment by aputtapa000** [comment]
Immediately fixed the problem and didn't even have to clear appdata folder. God bless! Probably should put this fix in a new version for the guys who aren't as techy. Anyway, thank you @danbob!

**Comment by Zloduh** [comment]
On ubuntu i cant edit the file. read only even with root account. 
Any advice?

**Comment by tlnd-laurent** [comment]
How do you fix this when you have install yakyak with snap ? I don't find the lib mentioned

**Comment by danbob** [comment]
@Zloduh you can make the file editable by root like so:
```bash
sudo chmod u+w /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js
```
I believe that's the correct path for Ubuntu but it will only complain if it's not.

**Comment by Zloduh** [comment]
@danbob 
`chmod: cannot access '/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js': No such file or directory`
i have found the file on different location
` /snap/yakyak/1/resources/app/node_modules/hangupsjs/lib/init.js`

when i try to edit that file i cant save it due to "read only file system" 
also chmod gave same error....
Perhaps there is some service that is blocking the write on the file.. yakyak is not running

**Comment by danbob** [comment]
Oh, you're using the Snap version. Snaps are self-contained filesystems, I don't know how to edit them or if they even can be edited. You might have to install the regular .deb version to use the workaround.

**Comment by christian-0s** [comment]
@Zloduh do the following:
create temp directory
cd that
sudo systemctl stop snap-yakyak-1.mount
unsquashfs /var/lib/snapd/snaps/yakyak_1.snap
vim squashfs-root/resources/app/node_modules/hangupsjs/lib/init.js
mksquashfs squashfs-root/ yakyak_1.snap -noappend -always-use-fragments
replace file in /var/lib/snapd/snaps/
sudo systemctl start snap-yakyak-1.mount
and that's it, yakyak working again. Thanks @danbob !

**Comment by 42degrees** [comment]
Changing the node_modules/hangupsjs/lib/init.js script worked on Windows 10 64-bit version 1.5.0.

**Comment by michaeljsorisi** [comment]
Fix didn't work for OSX El Capitan 10.11.6, although I'm not experienced in making these types of edits.

**Comment by yachan-mdsol** [comment]
This very same problem happened to me last week.  I thought it's the service having problem.  Found this and the fix work the magic for me.  (I'm on MacOS 10.12.6)

**Comment by clarkworld** [comment]
Thanks guys, this did the trick for me too. Great community here.

**Comment by mfagundez** [comment]
Thanks for the workaround. It works for me too!

**Comment by Dracks** [comment]
Thanks, it works!

**Comment by guslanzetta1** [comment]
Worked for me in Windows 10.

Tks!

**Comment by akhan23wgu** [comment]
Had this issue on MacOS Sierra allofasudden. The `html = html.replace(/<\/?script.*?>/gm, '');` replacement fixed it for me. Thanks @danbob!

**Comment by Spleeen** [comment]
Thanks @cristianoronan !

**Comment by jarrekmaar** [comment]
Worked for me on macOS 10.13.4

**Comment by juhasim** [comment]
Hi guys,

We appreciate the fast fix, but could we stop commenting this issue as it sends spam to everybody's emails. Fast fix, it works as promised. Thanks to developers.

**Comment by Spleeen** [comment]
@juhasim In fact, but you can also mute this thread and stop spam ;)

**Comment by sumnercreations** [comment]
This fix worked for me, now it's happening again and I've tried to kill the app and made sure the init file still has the change described, but the application still won't load. Stuck on connecting... :(

**Comment by DanLauer** [comment]
@sumnercreations Try installing the latest release and deleting %appdata%\yakyak folder.

**Comment by 188Alex188** [comment]
https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711

Solve the problem!

**Comment by xanthiia** [comment]
Hi guys, I have the very same issue. Yesterday YakYak was working, today it's not. I have Kubuntu 18.04 - I had a snap install, so I used the .deb package. Tried to edit the script, did not help. Tried to delete AppData AND the installation while the app was closed, deleted the .deb package of 1.5.2 version, downloaded 1.5.0, edited the script and still not working....does anyone have any idea?

Thanks a lot.

**Comment by juhasim** [comment]
Same problem here. Started occurring today.

**Comment by khairahee** [comment]
Same! I've just started to get the problem again. Tried updating the init.js and even installed the latest version via hombrew 

`brew caskroom install yakyak`

but to no avail. 

Any help would be appreciated

**Comment by danbob** [comment]
Unfortunately the changes they made this time are more difficult to work around. Some folks found a partial fix here: https://github.com/yakyak/yakyak/issues/979#issuecomment-432817986

**Comment by khairahee** [comment]
Sadly that didnt work for me :(

**Comment by PlatinumP** [comment]
**Yakyak does not work with MacOS Mojave, the above fixes do not seem to work!**

**Comment by Marek00Malik** [comment]
Again, after 1.5.1 with updated values were working. Updated with homebrew to 1.5.2 it stopped working again. 
What is the status of this issue ?

**Comment by danbob** [comment]
Google made more changes like the ones last week. There's a pull request pending that should prevent this particular issue from happening again: https://github.com/yakyak/hangupsjs/pull/107
