### ISSUE TITLE
connect_failed SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by elbrinke** [yakyak/yakyak#924]
Hi, 

I am running Yakyak on Kali Linux, which i have done for a while without any problems. 

When i installed 1.5.0, and tried to run it, i got the following errors:

```
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:877:14
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
reconnecting 0
```

**Comment by larstobi** [comment]
I got the same today on v1.4.3.

**Comment by frazor** [comment]
I tried fix in #918 on 1.4.4 (under macos, but should be the same fix once you find the file init.js really), and that worked. #919 will probably work too.

So html hotfix should really work under both versions, 1.4.4 and 1.5.0.

**Comment by elbrinke** [comment]
#918 worked for me too :). Thanks @frazor

**Comment by jkirklan** [comment]
Thanks @frazor  I'm on MacOS 10.13.4 and it fixed it.  Do we know if anyone has done a PR to fix this permanently?
