### ISSUE TITLE
SyntaxError: Unexpected string in JSON at position 946

### ISSUE THREAD

**Issue by pi-c426** [yakyak/yakyak#929]
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected string in JSON at position 946
    at JSON.parse (<anonymous>)
    at loadFromFile (/opt/yakyak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/opt/yakyak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/opt/yakyak/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/opt/yakyak/resources/app/main.js:49:12)
    at Object.<anonymous> (/opt/yakyak/resources/app/main.js:591:4)
    at Object.<anonymous> (/opt/yakyak/resources/app/main.js:595:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by ryanbrate** [comment]
I'm having the same problem here.....

ry@mintLaptop ~ $ flatpak run com.github.yakyak.YakYak
Gtk-Message: Failed to load module "atk-bridge"
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/app/lib/com.github.yakyak.YakYak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/app/lib/com.github.yakyak.YakYak/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/app/lib/com.github.yakyak.YakYak/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/app/lib/com.github.yakyak.YakYak/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/app/lib/com.github.yakyak.YakYak/resources/app/main.js:49:12)
    at Object.<anonymous> (/app/lib/com.github.yakyak.YakYak/resources/app/main.js:591:4)
    at Object.<anonymous> (/app/lib/com.github.yakyak.YakYak/resources/app/main.js:595:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by alfredodiaz** [comment]
Yakyak fails with this error since a week ago
```
> yakyak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /home/user/bin/yakyak-1.4.3/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:816:13)
    at /home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:877:14
    at runSingle (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:137:13)
    at flush (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /home/user/bin/yakyak-1.4.3/resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:816:13)
    at /home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:877:14
    at runSingle (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:137:13)
    at flush (/home/user/bin/yakyak-1.4.3/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by hnilsen** [comment]
Updated to 1.5.0 now, still the same:
`hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed SyntaxError: Unexpected token <
    at Object.bind.out (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:877:14
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error connecting SyntaxError: Unexpected token <
    at Object.bind.out (/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:62:23)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:63:26
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:877:14
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`
