### ISSUE TITLE
YakYak hangs on connecting forever

### ISSUE THREAD

**Issue by manzari** [yakyak/yakyak#982]
YakYak hangs on connecting forever after sign in.
Possible duplicate of:
#919 #981 #978 
```
connect_failed TypeError: Cannot read property 'length' of undefined
    at /snap/yakyak/28/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error connecting TypeError: Cannot read property 'length' of undefined
    at /snap/yakyak/28/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/snap/yakyak/28/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by fulltrucker** [comment]
#979 yakyak/hangupsjs#103

**Comment by fxalgrain** [comment]
Yes it's a duplicate with #981.

@manzari  Look to #981, you will have a working workarround ;)

**Comment by Gedrean** [comment]
Thanks to @HomerSp 's patches, on another issue that is the same as this issue, I have posted a set of steps that seem to fix this (applying the appropriate patched files) without the need to recompile.

This works for Win10 x64 but as others in the thread mention it works on Linux and Mac for them as well.

Here:

https://github.com/yakyak/yakyak/issues/981#issuecomment-433204393

**Comment by averissimo** [comment]
This is fixed in v1.5.2 that was just updated and released -- major thanks to contributors of this pull request: https://github.com/yakyak/hangupsjs/pull/104

Please report back if you guys have problems

**Comment by smet-dk** [comment]
I still seem to have this issue....
installed:   1.5.2 (31) 141MB -

**Comment by averissimo** [comment]
Did you download again after my comment?

Our release system so far is confusing and I'm looking forward to change it a bit, as we overwrite the binaries in the pre-release versions until they are released.

**Comment by smet-dk** [comment]
Sorry about that. Seems to work now.

**Comment by averissimo** [comment]
Great!!

**Comment by zgavin** [comment]
I'm also still having this issue.  Just re-downloaded 1.5.2

**Comment by Massbadetti** [comment]
Up until yesterday @ztoben 's fixes were working. Today it went back to "Connecting" forever so I replaced them with the latest Beta release you mention above ... and it still doesn't work (on Win10 x64). Deleted cache as well so I could reconnect to my google account but after that, still stuck at connecting. :-/

**Comment by smet-dk** [comment]
> Up until yesterday @ztoben 's fixes were working. Today it went back to "Connecting" forever

Same for me again...

**Comment by smet-dk** [comment]
> > Up until yesterday @ztoben 's fixes were working. Today it went back to "Connecting" forever
> 
> Same for me again...

Sorry: Ubuntu 18:04

**Comment by ztoben** [comment]
#999 has a fix in the comments.

**Comment by smet-dk** [comment]
Thank you @ztoben for the hint! Worked for Ubuntu 18.04 as stated in #999
