### ISSUE TITLE
App threw an error during load, Error: Cannot find module 'googleapis'

### ISSUE THREAD

**Issue by cmurf** [yakyak/yakyak#987]
Starting with https://github.com/yakyak/yakyak/issues/978 this is what I did to clean up and reinstall:

```
[chris@flap yakyak]$ git clean -fxd
Removing app/
Removing node_modules/
[chris@flap yakyak]$ git reset --hard origin/master
HEAD is now at ec04e5e add kde icons to gulpfile and correct naming
[chris@flap yakyak]$ npm install

> typechecker@2.0.8 preinstall /home/chris/Applications/yakyak/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/chris/Applications/yakyak/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> electron@3.0.3 postinstall /home/chris/Applications/yakyak/node_modules/electron
> node install.js


> hangupsjs@https://github.com/yakyak/hangupsjs/tarball/master postinstall /home/chris/Applications/yakyak/node_modules/hangupsjs
> npm run prepublish


> hangupsjs@1.3.6 prepublish /home/chris/Applications/yakyak/node_modules/hangupsjs
> coffee -o lib src

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 855 packages from 1518 contributors and audited 7457 packages in 11.648s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[chris@flap yakyak]$ npm run gulp

> yakyak@1.5.2 gulp /home/chris/Applications/yakyak
> gulp

[12:51:54] Failed to load external module coffeescript/register
[12:51:54] Requiring external module coffee-script/register
[12:51:54] Using gulpfile ~/Applications/yakyak/gulpfile.coffee
[12:51:54] Starting 'default'...
[12:51:54] Starting 'package'...
[12:51:54] Starting 'coffee'...
[12:51:54] Starting 'html'...
[12:51:54] Starting 'images'...
[12:51:54] Starting 'media'...
[12:51:54] Starting 'locales'...
[12:51:54] Starting 'icons'...
[12:51:54] Starting 'less'...
[12:51:54] Starting 'fontello'...
[12:51:54] Finished 'icons' after 69 ms
[12:51:55] Finished 'media' after 492 ms
[12:51:55] Finished 'images' after 613 ms
[12:51:55] Finished 'html' after 776 ms
[12:51:55] Finished 'less' after 784 ms
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[12:51:56] Finished 'locales' after 1.84 s
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[12:51:57] Finished 'coffee' after 2.43 sl pacote range manifest for plist@^2.0.0 fetched in 40ms
[12:51:57] Finished 'fontello' after 2.59 spacote range manifest for glob-watcher@^5.0.0 fetched in
npm WARN deprecated text-encoding@0.6.4: no longer maintained

> typechecker@2.0.8 preinstall /home/chris/Applications/yakyak/app/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/chris/Applications/yakyak/app/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> hangupsjs@1.3.7 postinstall /home/chris/Applications/yakyak/app/node_modules/hangupsjs
> npm run prepublish


> hangupsjs@1.3.7 prepublish /home/chris/Applications/yakyak/app/node_modules/hangupsjs
> coffee -o lib src

npm notice created a lockfile as package-lock.json. You should commit this file.
added 209 packages from 164 contributors and audited 7457 packages in 11.562s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[12:52:07] Finished 'package' after 13 s
[12:52:07] Finished 'default' after 13 s
[chris@flap yakyak]$ npm run electron app

> yakyak@1.5.2 electron /home/chris/Applications/yakyak
> electron "app"

App threw an error during load
Error: Cannot find module 'googleapis'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/chris/Applications/yakyak/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:18:12)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:362:4)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:364:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'googleapis'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/chris/Applications/yakyak/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:18:12)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:362:4)
    at Object.<anonymous> (/home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/auth.js:364:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
^C[chris@flap yakyak]$ 
```

Fedora 29
nodejs-10.12.0-1.fc29.x86_64
npm-6.4.1-1.10.12.0.1.fc29.x86_64

**Comment by averissimo** [comment]
Sorry, my bad. I left some code on the trunk after an experiment.

However, since some hours ago that this should not have an impact on yakyak as the direct dependency from github was removed (using npmjs package instead)

Please pull and perform `npm install` or `npm ci`

**Comment by cmurf** [comment]
Yep! It's working now, thanks!
