### ISSUE TITLE
Stuck at connecting

### ISSUE THREAD

**Issue by eblis** [yakyak/yakyak#991]
YakYak will no longer connect to my Google Hangouts account, stuck at "Connecting" forever.

```hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error connecting TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/opt/yakyak/resources/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by socketbox** [comment]
Have a look at #988. It could be that your problem has already been described there.

Also, the version of the app you're using is one minor release behind. Current version is 1.5.2

**Comment by eblis** [comment]
I don't have an option to upgrade yet (Linux Mint 19).
I had a quick look at the description in #988 before opening this, but the error reported there was different (did not check all the comments, will have a look now).

**Comment by howlermonkeys** [comment]
Same problem for me on Mac for the last few days as well.

**Comment by eblis** [comment]
I managed to get it working by removing everything from ~/.config/yakyak and then installing the latest prepackaged version (1.5.2)

**Comment by dikodahan** [comment]
I did not actually have a yakyak folder or file under ~/.config (I am running MacOS 10.14) but had the exact same issue with YakYak v1.5.2 installed.
However, I just downloaded v1.5.2 and overwrote the existing install and it solved the issue.

**Comment by cgtobi** [comment]
On macOS you can delete `~/Library/Application\ Support/yakyak`, download a fresh 1.5.2 and should be back up and running.

**Comment by eblis** [comment]
It started happening again, after it worked for a few days.

**Comment by dikodahan** [comment]
Same here. Happened again today.

**Comment by s3w47m88** [comment]
Me too.

**Comment by cgtobi** [comment]
[This](https://github.com/yakyak/yakyak/issues/999#issuecomment-434873957) solved the problem for me (at least for now).

**Comment by patefoniq** [comment]
Today I have the same problem. I'm using 1.5.7 version

**Comment by teicher** [comment]
please see https://github.com/yakyak/yakyak/issues/1177
