### ISSUE TITLE
YakYak refuses to start whatsoever

### ISSUE THREAD

**Issue by Kazuhirax3** [yakyak/yakyak#996]
I had cloned it from GitHub directly and ran the install command through shell. However, it threw a lot of errors during installation and will not start whatsoever, period. Attached is the npm-debug.log file that was generated along with a fetch to give system info.
![shot-2018-10-30_09-32-48](https://user-images.githubusercontent.com/43585582/47734050-d1b57c00-dc26-11e8-9fdf-54d2cfc67c4b.png)
[npm-debug.log](https://github.com/yakyak/yakyak/files/2530569/npm-debug.log)

**Comment by averissimo** [comment]
You are probably correct  @ztoben 

Current electron version requires node v10, can you try @Kazuhirax3

**Comment by llister15** [comment]
I have node -v10.10.0 and I am still having this issue. When I click on the launcher icon I get nothing when I try to run in the terminal I get nothing.

**Comment by llister15** [comment]
devturtle@devturtle-desktop:/opt/lampp/htdocs/yakyak$ npm start

> yakyak@1.5.3 start /opt/lampp/htdocs/yakyak
> gulp && electron app

[11:10:02] Failed to load external module coffeescript/register
[11:10:02] Requiring external module coffee-script/register
[11:10:03] Using gulpfile /opt/lampp/htdocs/yakyak/gulpfile.coffee
[11:10:03] Starting 'default'...
[11:10:03] Starting 'package'...
[11:10:03] Starting 'coffee'...
[11:10:03] Starting 'html'...
[11:10:03] Starting 'images'...
[11:10:03] Starting 'media'...
[11:10:03] Starting 'locales'...
[11:10:03] Starting 'icons'...
[11:10:03] Starting 'less'...
[11:10:03] Starting 'fontello'...
[11:10:03] Finished 'icons' after 70 ms
[11:10:04] Finished 'media' after 614 ms
[11:10:04] Finished 'images' after 829 ms
[11:10:04] Finished 'html' after 1.03 s
[11:10:05] Finished 'less' after 1.25 s
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[11:10:06] Finished 'locales' after 2.34 s fetch GET 200 https://registry.npmjs.org/sinon 61ms
[11:10:06] Finished 'coffee' after 2.76 sl pacote range manifest for concat-stream@^1.6.0 fetch
[11:10:06] Finished 'fontello' after 2.89 sfetch GET 200 https://registry.npmjs.org/flatmap-str
npm WARN deprecated text-encoding@0.6.4: no longer maintained

> hangupsjs@1.3.8 postinstall /opt/lampp/htdocs/yakyak/app/node_modules/hangupsjs
> npm run prepublish


> hangupsjs@1.3.8 prepublish /opt/lampp/htdocs/yakyak/app/node_modules/hangupsjs
> coffee -o lib src

sh: 1: coffee: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hangupsjs@1.3.8 prepublish: `coffee -o lib src`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hangupsjs@1.3.8 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devturtle/.npm/_logs/2018-11-08T19_10_10_122Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hangupsjs@1.3.8 postinstall: `npm run prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hangupsjs@1.3.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devturtle/.npm/_logs/2018-11-08T19_10_10_556Z-debug.log
[11:10:10] "npm" exited with non-zero code 1 , run `npm install --production` manually
[11:10:10] 'package' errored after 6.77 s
[11:10:10] Error: "npm" exited with non-zero code 1
    at ChildProcess.cmd.on.code (/opt/lampp/htdocs/yakyak/node_modules/gulp-install/lib/command-runner.js:14:25)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:460:23)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

[11:10:10] 'default' errored after 6.77 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yakyak@1.5.3 start: `gulp && electron app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yakyak@1.5.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devturtle/.npm/_logs/2018-11-08T19_10_10_621Z-debug.log

**Comment by llister15** [comment]
I downloaded the 1.5.3 deb package and it is still not starting. It shows in my docker for a few seconds then goes away never opens. Let me know what I should do

**Comment by averissimo** [comment]
My bad, I said previously said `npm ci` would work, but I was mistaken, try:

1. removing contents of `node_modules`
1. removing contents of `app/node_modules`
1. run `npm install`
1. run `npm start`

**Comment by llister15** [comment]
I was able to get it to compile but it still doesn't run I also tried the pre-compiled binaries and it's doing the same behavior it loads up the task icon for a few seconds and then it closes I never see the application screen at all. I tried to remove it and reinstall and still the same thing. I am running Elementary OS (Linux) just started doing this a few days ago. How do I check the logs to see why it is crashing.

**Comment by averissimo** [comment]
The bug you had before was due to coffee-script not being installed proper, a work around is to follow the steps above and should work.

An alternative would be to install coffe-script globally `npm i coffeescript -g`

But it seems like that's behind you right now.

You can try 2 things:

1. `npm run gulp && npm run debug` -- this will open a debugging console in yakyak's window
1. add a `bog` dependency *(`npm install --save bog`)* and the following code to `main.coffee`

```
require('bog').level('debug') # also debugs hangupsjs 
```

then paste the output of the console here... be careful to remove any identifying strings from the output.
