### ISSUE TITLE
Stuck at connecting...again

### ISSUE THREAD

**Issue by DanLauer** [yakyak/yakyak#999]
I updated to the re-release of 1.5.2 last week per #988. I just restarted Windows 10 and I'm back to stuck at connecting. Tried the latest beta build. Just connecting forever again.

**Comment by blackroseMD1** [comment]
Same. I tried deleting cookies.json, which used to fix the issue, but that didn't work.

**Comment by reaganking** [comment]
Confirming same issue as @DanLauer. Was working this morning. Same thing that happened last week.

**Comment by belthesar** [comment]
I am also experiencing this issue.  I opened the app from the binary in a terminal and was able to collect the following info from the console. Are there any other diagnostics or troubleshooting steps I can provide to help debug the issue? 

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of null
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:570:49
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of null
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:854:54)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:816:13)
    at /Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:570:49
    at runSingle (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:137:13)
    at flush (/Applications/YakYak.app/Contents/Resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by sturoid** [comment]
Same

**Comment by Bukimari** [comment]
Yep, same issue as last week. Google must have changed something again. Arch Linux 4.18.16

**Comment by robertdwilson** [comment]
Same here too.
Win 10 Pro x64

**Comment by brian163** [comment]
I saw this problem on macOS 10.3.6 this morning. Before coming to the forum, I downloaded "v1.5.3-beta-rolling" (which is also labelled 1.5.2?) and it works again. Not sure if that will help anyone here but thought I'd mention it.

**Comment by trenb** [comment]
@brian163 I tried both, neither works.

**Comment by brian163** [comment]
Ok, so I lied. Well, I didn't really but...

I had started another issue thread to inquire about the menu bar icon in macOS and in the process I quit YakYak to try something. When I went to start it up again, the "Connecting..." issue immediately returned.

Apologies but the rolling update version definitely resolved my connection issue earlier this morning, only to not connect again now. I suspect that is why @trenb was seeing a different result.

**Comment by akrawchyk** [comment]
https://github.com/yakyak/hangupsjs/issues/106

**Comment by tomasz-musialek** [comment]
@DanLauer @belthesar @trenb 

Please go to the following file in the YakYak directory

yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js

And make the change:

ds:20 to ds:19

Under BOTH the self_entity and conv_states.

Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

**Comment by blackroseMD1** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

This worked for me on Windows 10 x64.

**Comment by Wasca** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

This worked for me on Mac OSX 10.13.6

**Comment by devureta** [comment]
This work for me on Bunsenlabs
/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js

**Comment by adampatterson** [comment]
Same... Uninstalled ( last time that worked ) no luck.

**Comment by vcao** [comment]
Does this change apply to binaries as well or do we have to compile from source?

> > @DanLauer @belthesar @trenb
> > Please go to the following file in the YakYak directory
> > yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> > And make the change:
> > ds:20 to ds:19
> > Under BOTH the self_entity and conv_states.
> > Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.
> 
> This worked for me on Mac OSX 10.13.6

**Comment by peppermintesse** [comment]
The fix worked for me on macOS 10.13.6. 
/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js

**Comment by adampatterson** [comment]
Also worked for me.

**Comment by cmurf** [comment]
Edited lines 106 and 112 as described, no change, still fails on Fedora 29.

**Comment by clarkworld** [comment]
This worked for me, thanks for the solution. No way I would have got here on my own.

**Comment by samsol38** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Thanks my friend...

**Comment by minhaz1** [comment]
Worked for me on Mac:

```diff
--- /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js.bk       2018-10-31 23:05:23.000000000 -0700
+++ /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js  2018-10-31 23:05:33.000000000 -0700
@@ -103,13 +103,13 @@
               }
             },
             self_entity: {
-              key: 'ds:20',
+              key: 'ds:19',
               fn: function(d) {
                 return CLIENT_GET_SELF_INFO_RESPONSE.parse(d[0]).self_entity;
               }
             },
             conv_states: {
-              key: 'ds:20',
+              key: 'ds:19',
               fn: function(d) {
                 return CLIENT_CONVERSATION_STATE_LIST.parse(d[0][3]);
               }
```

**Comment by vmrm** [comment]
helped me on Ubuntu 18.04

**Comment by jeremycherfas** [comment]
Worked for me on Mac

**Comment by kli0rf** [comment]
That worked for Fedora 29.

**Comment by emmandyar** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

This fixes it for me as well, KDE Neon

**Comment by plessbd** [comment]
I applied https://github.com/yakyak/hangupsjs/pull/107 and put the source for [init.js](https://gist.githubusercontent.com/plessbd/7aa1c90ec9bf8fa6712e676cffbf77e0/raw/7a7b25c9d874ec3a80267e130834da81c55000a8/init.js) up on gist if you want you can download that and replace it in `/<path to yakyak resource>/node_modules/hangupsjs/lib`

On mac this is generally `/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib`

as @HomerSp says

> This should be a lot more reliable and will, hopefully, survive future server-side updates (like one last night).

**Comment by hell-spawn** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

This worked for me in Ubuntu 18.04 TLS

**Comment by devauxb** [comment]
@DanLauer @belthesar @trenb

Please go to the following file in the YakYak directory

yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js

And make the change:

ds:20 to ds:19

Under BOTH the self_entity and conv_states.

Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Thank you Dan, this worked for me on Mac OSX 10.14.1

**Comment by shakeme** [comment]
> ds:20 to ds:19
Thank you. This also works for me on Mac OSX 10.13.6

**Comment by belthesar** [comment]
I can also confirm that the patch works.  Thanks!

**Comment by wowthatisrandom** [comment]
confirmed as well, appreciate it

**Comment by Gorklax** [comment]
Thank you so much! You guys always get on this stuff so quick.

**Comment by spencerhughes** [comment]
Changing
`ds:20 to ds:19`
for self_entity and conv_states fixed it for me.
macOS 10.13.6

**Comment by mrvkino** [comment]
macOS 10.14.1
The change fixed the issue for me also.

**Comment by Setitie** [comment]
Glad it's working for everyone. Looking forward to a fix for us Windows noobs.

**Comment by TheDavidJohnson** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Thanks! Worked on Ubuntu 18.04. My app is installed in `/opt/yakyak/`, so my full path to `init.js` was:
```
/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js
```
Appreciate it!

**Comment by petrklus** [comment]
Worked in macOS here too

**Comment by Gedrean** [comment]
Win10 x64 Pro.  The fixes by @tomasz-musialek worked for me.

@Setitie: Open your YakYak folder, open 'Resources', open 'App', open 'Node_modules', open 'hangupsjs', right click 'init.js' and choose Edit which will open 'init.js' in Notepad, ctrl+F and find 'self_entity'.  Shortly after that (because notepad can't show new lines right in these files) will be the letters ds:20, change that 20 to a 19.  Do ctrl+f again, find 'conv_states'.  Same thing, ds:20 to ds:19 RIGHT after it.

It'll look like this:
`self_entity: {              key: 'ds:20'`

You can do it!  I believe in you!

**Comment by clearscreen** [comment]
Hopefully https://github.com/yakyak/hangupsjs/pull/107 will fix this in a more permanent way.

**Comment by SovereignGFC** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Worked for me on Windows 10 x64 after YakYak stopped connecting again.

**Comment by RemyFV** [comment]
fix by @tomasz-musialek worked on win10 x64 with the latest release (mislabeled rolling 1.5.3).

thanks a lot, tomasz.

**Comment by patefoniq** [comment]
Yes, it solves the problem. Thank you.

**Comment by davidsedlar** [comment]
Is this because of Google changing the protocol or why are there so many of these problems lately? I have a feeling this fix is also going to be obsolete as soon as Google changes something again.

**Comment by HomerSp** [comment]
Yes, they are doing changes server-side. Not really sure why they have been doing these changes, but the data that hangupsjs pulls was never intended to be used this way. I have created a pull request for hangupsjs that removes the reliance on the ds keys though, so once that's merged to master I am hoping that these problems should be completely eliminated (until they do more extensive changes).

**Comment by Dawson19** [comment]
yes, it works for me.

try this out, if you need.

Thanks for help.

**Comment by Dawson19** [comment]
Thanks for help, try this out. Please.

**Comment by Setitie** [comment]
Was off work sick for a little bit. Finally did the above CTRIL F thing and worked great. Thank you

**Comment by RedPenguin2** [comment]
The ds:19 issue fixed me right up on Ubuntu 18.04 LTS 64bit.

It was even better than 2 days ago.

The fix with ds's that I applied before got yakyak working mostly but now, my entire conversation list and history completely shows. Before it was just only conversations I had recently in YakYak, older inactive ones would not show.

**Comment by orion4444** [comment]
Confirmed ds:19 fix works on Windows.

**Comment by fulltrucker** [comment]
> I applied [yakyak/hangupsjs#107](https://github.com/yakyak/hangupsjs/pull/107) and put the source for [init.js](https://gist.githubusercontent.com/plessbd/7aa1c90ec9bf8fa6712e676cffbf77e0/raw/7a7b25c9d874ec3a80267e130834da81c55000a8/init.js) up on gist if you want you can download that and replace it in `/<path to yakyak resource>/node_modules/hangupsjs/lib`
> 
> On mac this is generally `/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib`
> 
> as @HomerSp says
> 
> > This should be a lot more reliable and will, hopefully, survive future server-side updates (like one last night).
> 
> Please dont trust me and look at what you are downloading before applying it.
> For those that dont here is all I did from within `/<path to yakyak resource>/node_modules/hangupsjs`
> 
> ```
> wget https://patch-diff.githubusercontent.com/raw/yakyak/hangupsjs/pull/107.patch
> patch -p1 < 107.patch
> rm -rf lib/*
> npm i
> ```

Confirming that applying the patch from yakyak/hangupsjs#107 to [v1.5.3-beta-rolling](https://github.com/yakyak/yakyak/tree/v1.5.3-beta-rolling) as described above and compiling hangupsjs (that's the {{npm i}} part, right?) fixes this issue i.e. enables YakYak to connect to Google Hangouts and function as expected. Mac OS X 10.11.6 El Capitan. Arriba!

**Comment by omnimon** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Worked on Ubuntu 16.04 LTS. Why won't make this as an official hotfix then?

**Comment by StevenSeiden** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.
> 
> Thank you Dan, this worked for me on Mac OSX 10.14.1

This fix also works for me on macOS 10.14

**Comment by mobiusint** [comment]
The below worked for me on OS X Mojave 10.14.1

> ds:20 to ds:19
> Under BOTH the self_entity and conv_states.

**Comment by EzTargetUK** [comment]
I'm still getting the connecting ... issue after following all the steps above (using the latest 1.5.3-BETA download, changing the ds;20 to ds:19). I'm even getting the following when attempting to start YakYak from the command line:

C:\Tools\yakyak>yakyak

C:\Tools\yakyak>
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at C:\Tools\yakyak\resources\app\node_modules\hangupsjs\lib\init.js:125:20
    at _fulfilled (C:\Tools\yakyak\resources\app\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Tools\yakyak\resources\app\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Tools\yakyak\resources\app\node_modules\q\q.js:816:13)
    at C:\Tools\yakyak\resources\app\node_modules\q\q.js:570:49
    at runSingle (C:\Tools\yakyak\resources\app\node_modules\q\q.js:137:13)
    at flush (C:\Tools\yakyak\resources\app\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error connecting TypeError: Cannot read property 'length' of undefined
    at C:\Tools\yakyak\resources\app\node_modules\hangupsjs\lib\init.js:125:20
    at _fulfilled (C:\Tools\yakyak\resources\app\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Tools\yakyak\resources\app\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Tools\yakyak\resources\app\node_modules\q\q.js:816:13)
    at C:\Tools\yakyak\resources\app\node_modules\q\q.js:570:49
    at runSingle (C:\Tools\yakyak\resources\app\node_modules\q\q.js:137:13)
    at flush (C:\Tools\yakyak\resources\app\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I added an if(d){} block around the if block on the line above, and was able to get YakYak to run and log in but there was no chat messages.

I'm using the WIndows 10 x64 prebuilt libraries.

**Comment by corbinschwartz** [comment]
Followed the steps outlined by @fulltrucker, can confirm fixed on macOS 10.13.6

**Comment by cproxy** [comment]
the ds:19 work for me yesterday, today I get the following.  The changes are still in place.
![yakyaksad](https://user-images.githubusercontent.com/44812073/48076215-93c1d600-e199-11e8-8d12-595c7b537067.gif)

**Comment by sfoley-gpqa** [comment]
Changing ds:20 to ds:19 didn't work for me at first (OSX 10.12.6, YakYak 1.5.2). When I opened the application, it spent ~20 seconds trying to connect and then slooooowly transitioned to the main screen with the white/grey/green bars but there were no other UI elements (no friend names/icons/text anywhere).

When I deleted the application from ~/Applications/ and replaced it with a newly-downloaded one (after making the ds:20 to ds:19 change), it started working.

Thank you for the fix!

**Comment by stealthybox** [comment]
This solution worked for me on MacOS Sierra:
https://github.com/yakyak/yakyak/issues/999#issuecomment-435510495

**Comment by dikodahan** [comment]
> @DanLauer @belthesar @trenb
> 
> Please go to the following file in the YakYak directory
> 
> yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js
> 
> And make the change:
> 
> ds:20 to ds:19
> 
> Under BOTH the self_entity and conv_states.
> 
> Make sure to "killall yakyak" on Linux (or kill all YakYak processes on any other system) and it should work fine, until Google changes that again.

Worked for me as well on MacOS 10.14.1 (Mojave)

**Comment by averissimo** [comment]
Sorry for the delay in tackling this

The rolling release is building as of now and after checking that it works we'll release a stable version.

Big thanks to @HomerSp for patching it up again!

**Comment by hradec** [comment]
I've made the changes of self_entity ('ds:21')  and conv_states('ds:20') to 'ds:19' as proposed here.
It wasn't enough to start yakyak in Linux, so I've made this old change as well:
```
if (d.length)  
```
to 
```
if (typeof d !== "undefined" && d !== null ? d.length : void 0) {
```

which then made it start up and show me this: 
![image](https://user-images.githubusercontent.com/806743/48218278-61051280-e33e-11e8-8345-f3ca26ed19a8.png)


Almost there... LOL

any more ideas? (I'm running it on Arch Linux, up2date as of yesterday!)

**Comment by rwaight** [comment]
Have you updated to 1.5.2?  I just updated to 1.5.2, then made the (`self_entity=DS:19` and `conv_states=ds:19`) changes to `init.js`.  It is connecting just fine now.

**Comment by sfoley-gpqa** [comment]
> I've made the changes of self_entity ('ds:21') and conv_states('ds:20') to 'ds:19' as proposed here.
> It wasn't enough to start yakyak in Linux, so I've made this old change as well:
> 
> ```
> if (d.length)  
> ```
> to
> 
> ```
> if (typeof d !== "undefined" && d !== null ? d.length : void 0) {
> ```
> which then made it start up and show me this:
> ![image](https://user-images.githubusercontent.com/806743/48218278-61051280-e33e-11e8-8345-f3ca26ed19a8.png)
> 
> Almost there... LOL
> 
> any more ideas? (I'm running it on Arch Linux, up2date as of yesterday!)

That exact thing happened to me as well. I uninstalled the application, reinstalled from a new (same version) file from Github, did the hack to init.js and it's working again for me (OSX Sierra)

**Comment by averissimo** [comment]
@hradec and @sfoley-gpqa this seems to be a different problem

**Comment by willgleich** [comment]
looks like I am having the issue again. :(

**Comment by mateusz-** [comment]
Looks like ds:18 is the new magic value.

**Comment by Setitie** [comment]
> Looks like ds:18 is the new magic value.

As per Mateusz, I updated the DC values to 18 and works again. Thank you Mateusz

**Comment by jbartolozzi** [comment]
> > Looks like ds:18 is the new magic value.
> 
> As per Mateusz, I updated the DC values to 18 and works again. Thank you Mateusz

As of 11/14 I was having this hanging connection issue again.
This fixed it.

**Comment by jroddy187** [comment]
> Looks like ds:18 is the new magic value.

Thank you. DS18 is the correct answer. Google needs to give me an official (free) app for Mac or stop messing with this.

**Comment by tomasz-musialek** [comment]
@Setitie @jbartolozzi @jroddy187 

The newest "**v1.5.4 Beta rolling**" release seems to have it fixed and should be more resistant against future protocol changes by Google.

You may try downloading the new **v1.5.4 Beta rolling** release at:

https://github.com/yakyak/yakyak/releases

**Comment by dikodahan** [comment]
The rolling beta is the one I've been using for the last few days on 10.14.1 and didn't have any additional issues with it.

**Comment by robertdwilson** [comment]
Logged in this morning and realized I too was having the same issue as everyone else.
Followed @tomasz-musialek link to the rolling beta and I'm all set now.
Thanks!!!

**Comment by averissimo** [comment]
v1.5.3 in the releases should also be working fine.

The only difference in the rolling release can be seen on OSX tray icon title *(which has been removed)*.

**Comment by claire-w** [comment]
@jroddy187 
Thank you ! Changing to ds:18 worked for me (on arch linux)

**Comment by mwitzenm** [comment]
FYI:  I was seeing the same behavior with my company sso auth'd id.  I could login via a regular controlled id from google but not my company id with sso.
